//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppMC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario_Rol
    {
        public System.Guid Usuario_Id { get; set; }
        public System.Guid Rol_Id { get; set; }
        public System.DateTime fecha_caducidad { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> Created_At { get; set; }
        public Nullable<System.DateTime> Updated_At { get; set; }
    
        public virtual Rol Rol { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
